title: "Creating Order out of Chaos"
tagline: "Learning, creating, sharing"

description: "This is my personal space for expressing ideas, sharing knowledge and experiences. Everything here is just an opinion."

url: "https://pavelbrm.com"
baseurl: ""
permalink: "pretty"
paginate: 10

author:
  name: "Pavel Brm"

twitter_username: "pavelbrm"
github_username: "pavelbrm"

excerpt_separator: "<!--more-->"

timezone: "UTC"

version: 0.1.0
updated_at: "14.06.2020"

plugins:
  - "jekyll-paginate"

exclude:
  - "LICENSE"
  - "README.md"
  - "docker-compose.yml"

custom_pages:
  tags: "/tags/"
  categories: "/categories/"
